# Generated by Django 5.2.4 on 2025-07-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pequena Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_images/', verbose_name='Imagem do Projeto')),
                ('link_to_repo', models.URLField(blank=True, null=True, verbose_name='Link do Repositório (Ex: GitHub)')),
                ('link_to_demo', models.URLField(blank=True, null=True, verbose_name='Link da Demonstração (Live Demo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicar Projeto?')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
